name: Scala CI
on:
  push:
    branches: [ "master", "scala-2.13" ]
  pull_request:
    branches: [ "master", "scala-2.13" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: olafurpg/setup-scala@v11
    - name: Run tests
      run: sbt test
      # Optional: This step uploads information to the GitHub dependency graph and unblocking Dependabot alerts for the repository
      #- name: Upload dependency graph
      # uses: scalacenter/sbt-dependency-submission@ab086b50c947c9774b70f39fc7f6e20ca2706c91
